### ISSUE TITLE
Multiplayer capability

### ISSUE THREAD

**Issue by gwario** [jonathan-laurent/AlphaZero.jl#101]
Hi,
i'm working on a game that allows for up to 4 players...

As i see it, it would be possible to do that by modifying the mcts code (add random rollouts for each player, ...) and the game and benchmark interfaces of course...

If anyone has thought about it, can you maybe share your thoughts on how it could be done? :D

Thanks!

**Comment by jonathan-laurent** [comment]
Thanks for your interest in AlphaZero.jl!

Solving games with more than two players is usually pretty messy as it isn't even clear what an optimal strategy is then. For example, what is keeping two players from teaming up against a third player for example?

Also, MCTS pretty much relies on the fact that there is a unique reward signal, which is the case in one player and two-player zero-sum games. It may be possible to generalize MCTS to your setting but how to do so seems pretty open to me.

**Comment by gwario** [comment]
> 
> Solving games with more than two players is usually pretty messy as it isn't even clear what an optimal strategy is then. For example, what is keeping two players from teaming up against a third player for example?
> 
> Also, MCTS pretty much relies on the fact that there is a unique reward signal, which is the case in one player and two-player zero-sum games. It may be possible to generalize MCTS to your setting but how to do so seems pretty open to me.

Thanks, I'm going through some papers right now....
Hope to get some specific options...
The game is also if imperfect information, which adds another layer of complication
