### ISSUE TITLE
6 dependencies errored

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#112]
Very interesting project, but there's an issue.

Environment: julia version 1.7.2, Ubuntu 18.04, NVIDIA GeForce GTX 1650/PCIe/SSE2 (GPU drivers were installed and work well with Python's libraries)

I ran for the first time:
julia --project -e 'import Pkg; Pkg.instantiate()'

and got:
Precompiling project...
  ✗ ChainRules
  ✗ CUDA
  ✗ NNlibCUDA
  ✗ Zygote
  ✗ Flux
  ✗ AlphaZero
  158 dependencies successfully precompiled in 77 seconds (4 already precompiled)
  6 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

What will I do? Thanks

**Comment by StepHaze** [comment]
With which version of Julia did you test AlphaZero.jl project?

**Comment by jonathan-laurent** [comment]
I just tested AlphaZero.jl with Julia 1.7.2 and did not run into a problem.
Note that if you are running into some problems compiling dependencies, the issue is with those dependencies and not with AlphaZero.jl.

**Comment by StepHaze** [comment]
> I just tested AlphaZero.jl with Julia 1.7.2 and did not run into a problem. Note that if you are running into some problems compiling dependencies, the issue is with those dependencies and not with AlphaZero.jl.

How do you run it?
I ran it so:

git clone --branch v0.5.0 https://github.com/jonathan-laurent/AlphaZero.jl.git
cd AlphaZero.jl
julia --project -e 'import Pkg; Pkg.instantiate()'

**Comment by dave7895** [comment]
What do you see when you run the suggested `import Pkg; Pkg.precompile()`?
assuming you instantiated the env, run and see if it still errors, and if it does what the exact errors are.
```
cd AlphaZero.jl
julia --project
julia> import Pkg
julia> Pkg.precompile()
```
