### ISSUE TITLE
How important is GI.vectorize_state function?

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#119]
For example, in mancala/game.jl:

`function GI.vectorize_state(::GameSpec, state)
  board = state.curplayer == WHITE ? state.board : flip_colors(state.board)
  function cell(pos, chan)
    if chan == :nstones
      return read_pos(board, pos)
    elseif chan == :whouse
      return isa(pos, HousePos) && pos.player == WHITE
    elseif chan == :wstore
      return isa(pos, StorePos) && pos.player == WHITE
    elseif chan == :bhouse
      return isa(pos, HousePos) && pos.player == BLACK
    elseif chan == :bstore
      return isa(pos, StorePos) && pos.player == BLACK
    end
    @assert false
  end
  positions = [
    [HousePos(WHITE, i) for i in NUM_HOUSES_PER_PLAYER:-1:1];
    [StorePos(WHITE)];
    [HousePos(BLACK, i) for i in NUM_HOUSES_PER_PLAYER:-1:1];
    [StorePos(BLACK)]]
  return Float32[
    cell(p, c)
    for p in positions,
        y in 1:1,
        c in [:nstones, :whouse, :wstore, :bhouse, :bstore]]
end`

Is it efficient or is there another idea of vectorize_state?
Unfortunately I have no experience with vectorization of a board state((

**Comment by StepHaze** [comment]
Ok, let's look at tic-tac-toe:
function GI.vectorize_state(::GameSpec, state)
  board = state.curplayer == WHITE ? state.board : flip_colors(state.board)
  return Float32[
    board[pos_of_xy((x, y))] == c
    for x in 1:BOARD_SIDE,
        y in 1:BOARD_SIDE,
        c in [nothing, WHITE, BLACK]]
end

It returts for the initial position this:
[1.0 1.0 1.0; 1.0 1.0 1.0; 1.0 1.0 1.0;;; 0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0;;; 0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]

I don't understand why it's filled with 1.0 at the beginning? It's completely empty

**Comment by gwario** [comment]
Maybe you are missing comments in the code...
```
# Vectorized representation: 3x3x3 array
# Channels: free, white, black
# The board is represented from the perspective of white
# (as if white were to play next)
```
so the first layer indicates empty fields

**Comment by gwario** [comment]
> How important is GI.vectorize_state function?

It constructs the input to the neural network from the current state of the game. So it is essential
