### ISSUE TITLE
When exploring a position, what these abbreviations mean?

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#121]
When exploring a position, what these abbreviations mean:

Nmcts
Vnet
Pmcts
Pnet
UCT (I believe it's Upper Confidence bounds applied to Trees)
Qmcts
Qnet

**Comment by StepHaze** [comment]
Also what are Lv, Lp, Lreg, Linv, Hp, Hpnet ?

**Comment by gwario** [comment]
These abbreviations are the properties of the Monte Carlo Tree Search....
If you check out the paper, there is an explanation of the MCTS algorithm: https://www.nature.com/articles/nature24270.epdf?author_access_token=VJXbVjaSHxFoctQQ4p2k4tRgN0jAjWel9jnR3ZoTv0PVW4gB86EEpGqTRDtpIz-2rmo8-KG06gqVobU5NSCFeHILHcVFUeMsbvwS-lxjqQGg98faovwjxeTUgZAUMnRQ

It will become clear....
N is the visit count, V the value (win/loss), ...
