### ISSUE TITLE
Cloud service for AlphaZero.jl

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#122]
Please recommend a mighty cloud service for AlphaZero.jl (with Julia support, of course). My laptop with GPU (NVIDIA GeForce GTX 1650) seems to be inefficient and can't solve the task.

**Comment by BE-Code** [comment]
Here's one option: https://colab.research.google.com/drive/1UbL2A-56rxr4UwxLk-uWyZ2i88nNmyQk?usp=sharing

**Comment by BE-Code** [comment]
No I haven't, but I am planning on it. If you know what command is needed to add the dependency, just put an exclamation mark in front of it and it will run it.
