### ISSUE TITLE
Number of network parameters

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#126]
In the beginning of a training:
    Number of network parameters: 2,222,986
    Number of regularized network parameters: 2,218,432
    Memory footprint per MCTS node: 352 bytes

How is the Number of network parameters computed? Is there a way to decrease it?

**Comment by gwario** [comment]
I'm not sure how exactly it is computed, but its the number of weights and so on, that your neural network is composed of... so in the AlphaZero ResNet architecture it depends on the number of filters and residual blocks. In SimpleNet it is influenced by `width`, `depth_common`, `depth_phead` and `depth_vhead`.
If you decrease the values in your ResNetHP or SimpleNetHP, the number of network parameters should decrease
