### ISSUE TITLE
MCTS.RolloutOracle(gspec)

### ISSUE THREAD

**Issue by DmitriMedved** [jonathan-laurent/AlphaZero.jl#145]
When we make a script containing the following:
gspec = Examples.games["tictactoe"]
mcts = MCTS.Env(gspec, MCTS.RolloutOracle(gspec))
computer = MctsPlayer(mcts, niters=1, timeout=1.0, τ=ConstSchedule(0.5))
explore(computer, gspec)
We run vanilla untrained Mcts, correct?

What do I need to write instead of MCTS.RolloutOracle(gspec) to run Mcts based on a trained model (from sessions folder)?

**Comment by DmitriMedved** [comment]
Any thoughts?

**Comment by DmitriMedved** [comment]
Please help me

**Comment by DmitriMedved** [comment]
Help please

**Comment by jonathan-laurent** [comment]
Instead of using `RolloutOracle`, you would need to pass a network oracle.
I recommend you to look at the definition of `AlphaZeroPlayer` in `training.jl`.

**Comment by DmitriMedved** [comment]
Please show me the example

**Comment by jonathan-laurent** [comment]
I am sure you can manage to figure this out on your own given the hints that I provided!
Remember that I am contributing to AlphaZero.jl on my own free time and that the time I spend answering questions is time I cannot spend improving the library. You should not expect me to spend more time answering your questions than you spent writing them.

**Comment by DmitriMedved** [comment]
I highly recommend you to create more clear examples so that we have fewer questions.
