### ISSUE TITLE
Game proposition: BonbonRectangle

### ISSUE THREAD

**Issue by smart-fr** [jonathan-laurent/AlphaZero.jl#149]
Hello AlphaZero.jl team,
I made a cute 2-players zero-sum game with complete information on my free time: https://bonbonrectangle.com.
It is easy to play, but quite complex in terms of combinatorics. It has offered interesting challenges to the nascent community around it. 😉
Two years ago, I discovered the Julia language and the amazing AlphaZero.jl framework. I implemented my game according to AlphaZero.jl v0.5, in the hope I would train an agent which would power a solo mode for my game. Unfortunately, my hardware at the time, my skills in AI, and the quantity of my free time were insufficient for me to succeed.
Now that a tutorial was integrated in the game and it's easier to talk about it, I want to give this goal another try. But I'd rather do it with the help of knowledgeable people. I wonder if anyone would see a scientific interest, or just a new entertaining project, in following that path with me?
Apologize if this request isn't posted where it should. I would be happy to submit it in a more appopriate environment.
I hope you understand this is not an automated post -you can check that this is not my first "Issue" here.
Thanks for reading!
Stéphane

**Comment by jonathan-laurent** [comment]
This game looks super interesting and I hope you find people to team up with you and try AlphaZero on it!
I am leaving this issue open.

**Comment by smart-fr** [comment]
Thank you Jonathan for your kind comment!
Don't hesitate to advertize the BonbonRectangle/AlphaZero project in your circle. 😉
Cheers

**Comment by smart-fr** [comment]
So now I have finished debugging the "game.jl" code of AlphaZero.jl game interface.
This implementation successfully passes the test_game script, so there's no obvious flaw.
However, the dummy_run script seems to never converge. Somehow Julia gets lost while building the NN in the ResNet function. Maybe because the game states and possible actions are quite large.

I must admit I am not going to become an AI expert in order to solve this problem and the subsequent ones which may impede the creation of an agent able to efficiently play [BonbonRectangle](https://www.bonbonrectangle.com).
Hence, I am calling for volunteers interested in creating a strong opponent for this game. I'll provide access and all explanations regarding my Julia source code, along with consulting, for free -in exchange of the possibility to use the created agent in my future commercial app.

Anyone interested?

**Comment by smart-fr** [comment]
I finally achieved what I wanted, thanks to your wonderful work. Thank you again. Closing the issue, and reporting in "Success stories".
