### ISSUE TITLE
Support for OpenSpiel games?

### ISSUE THREAD

**Issue by lanctot** [jonathan-laurent/AlphaZero.jl#15]
Hi Jonathan! 

I am a lead contributor to OpenSpiel, a framework for RL in games. OpenSpiel is a general game framework and we have a Julia API thanks to @findmyway. Someone from our team, @michalsustr, pointed me to your project. Looks great! 

We have many games implemented and tested I wonder if it would be possible to add support for them in your project? For the next two weeks, we are doing a concentrated effort in adding functionality to OpenSpiel.. might be a good time to look at this if anybody is interested (see https://github.com/deepmind/open_spiel/issues/251).

Curious to hear your thoughts on this!

**Comment by jonathan-laurent** [comment]
Thanks for reaching out!

In fact, I am working on adding support for OpenSpiel right now.
The reason it's been taking some time is that the current game interface relies pretty strongly on the assumption that games must be symmetric (the rules are the same for both players), which makes it incompatible with OpenSpiel's interface.

Once this restriction is lifted, adding support for OpenSpiel should be pretty easy.

**Comment by findmyway** [comment]
I just made a release of OpenSpiel_jll yesterday to use the latest stable version. https://github.com/JuliaPackaging/Yggdrasil/pull/1190 .  So `]add OpenSpiel` should just use the latest API on Linux.

Glad to see that you've made a lot of progress since our last discussion. You can check first https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/open_spiel.jl either you'd like to use this high-level API or write your own wrapper from scratch.

One thing to note is, just like I said in https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/19#issuecomment-647246641 , it would make functions more flexible to remove some unnecessary type restrictions. In most cases, `AbstractVector` would be enough.

Another thing to always keep in mind is that, some variables are **0-based**, not **1-based** in OpenSpiel.jl (like player_id, action_id).

Feel free to let me know if I can do anything to help here 😉

**Comment by jonathan-laurent** [comment]
@findmyway I just finished implementing the changes we discussed to the game interface (such as removing the board/state distinction an the symmetry assumption). I think the path is now clear to add support to OpenSpiel.jl and CommonRLInterface.jl. I'll keep you updated on this!

**Comment by christianjans** [comment]
Hi @jonathan-laurent, how is this going? No rush, just curious.

**Comment by jonathan-laurent** [comment]
@christianjans Thanks for your interest. I had put this issue on standby as my priority last month was to add support for distributed computing (see the [JuliaComputing demo](https://www.youtube.com/watch?v=JVUJ5Oohuhs)). Now that this is done, I can work on OpenSpiel support again. :-)

@findmyway I was thinking about something. In MCTS, I have to regularly store states and reset the environment to previously stored states. States should be comparable and hashable. Is OpenSpiel.jl currently supporting all of this?

**Comment by findmyway** [comment]
> States should be comparable and hashable. Is OpenSpiel.jl currently supporting all of this?

No, currently comparing two states will fall back to comparing the memory address. (We may added it if necessary.)

@lanctot  If I understand it correctly, the only way to compare two states is to compare the string format after calling `serialize(state)`, right?

**Comment by lanctot** [comment]
That's currently the heaviest way because it can write out a lot (more than necessary for comparing states). I would recommend using `ToString` to compare states. We can also add `operator==` (or some othe method/interface) which can default to comparing via the `ToString` but can be overridden if speed is a problem. We can also add a hashing for states which defaults to hashing the `ToString` but can be similarly overridden.

Let me know what makes the most sense for your use case and I will discuss it with the team.

**Comment by jonathan-laurent** [comment]
@findmyway Any update on this?

**Comment by findmyway** [comment]
I released a new version ([OpenSpiel@v0.1.2](https://github.com/JuliaReinforcementLearning/OpenSpiel.jl/pull/7)) with the patch of https://github.com/JuliaReinforcementLearning/OpenSpiel.jl/pull/7

<hr>

Currently https://github.com/JuliaReinforcementLearning/OpenSpiel.jl diverges slightly from https://github.com/deepmind/open_spiel/tree/master/open_spiel/julia I'll try to register this package directly in `deepmind/open_spiel` with the new feature ([registering-a-package-in-a-subdirectory](https://github.com/JuliaRegistries/Registrator.jl#registering-a-package-in-a-subdirectory) to avoid code duplication.

**Comment by findmyway** [comment]
FYI:

https://github.com/deepmind/open_spiel/issues/399

**Comment by jonathan-laurent** [comment]
Update: support for CommonRLInterface.jl is finally merged on master.
It should be easy to use AlphaZero.jl on OpenSpiel.jl games now.

**Comment by jonathan-laurent** [comment]
@michelangelo21 just contributed an OpenSpiel.jl wrapper for AlphaZero.jl along with a tic-tact-toe example.
I am closing this issue but please don't hesitate to reopen it if you have questions or encounter some rough edges!
