### ISSUE TITLE
num_filters=128

### ISSUE THREAD

**Issue by DmitriMedved** [jonathan-laurent/AlphaZero.jl#150]
By default, params.jl contains:
netparams = NetLib.ResNetHP(
  num_filters=128

With non-trivial games it often leads to Out of Memory error. If I decrease num_filters to 64, how will it affect to the learning and self-playing process?

**Comment by jonathan-laurent** [comment]
As usual with deep learning, this is hard to say precisely.
Larger networks can learn more complex policies and tend to generalize better in some cases.
How the network size affects performances should really be evaluated on a case-by-case basis.
