### ISSUE TITLE
NVIDIA GeForce GTX 1650 isn't good?

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#151]
For pretty complex, non-trivial games NVIDIA GeForce GTX 1650 isn't enough?
I decreased the number_games, num_filters, num_workers, etc, but keep getting "Killed" error message (Linux) during self-playing or learning.

**Comment by jonathan-laurent** [comment]
This GPU should be enough for simple games if you reduce some hyperparameters.
In addition to the ones you mention, reducing batch_size may also help.
I cannot help you much more without more details though.
