### ISSUE TITLE
What's the best OS for AlphaZero.jl ?

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#153]
I have Ubuntu 18.04/20.04.

When I run:
export GKSwstype=100
julia --project -e 'import Pkg; Pkg.instantiate()'

196 of 200 libraries are compiled. ChainRules, Zygote, Flux and AlphaZero are not compiled.

What's the best OS for AlphaZero.jl ?

**Comment by jonathan-laurent** [comment]
AlphaZero.jl should work on all OSes.
In particular, I just tested it on Ubuntu 20.04 and it works.

Can you try again to instantiate the `#master` version on a fresh environment?
If you still encounter an error, can you include it in your post?

**Comment by StepHaze** [comment]
I deleted Manifest.toml and everything was compiled. Is it the right way?

**Comment by jonathan-laurent** [comment]
Yes. I removed the Manifest myself in master.
In theory, the Manifest should guarantee repeatability but the previous Manifest was from an older version that does not specify the Julia version that was used.
