### ISSUE TITLE
Trouble installing AlphaZero.jl

### ISSUE THREAD

**Issue by smart-fr** [jonathan-laurent/AlphaZero.jl#156]
Hi, and Happy New Year. :-)
AlphaZero.jl might need an update following Julia 1.8.4 release. I wanted to go for a fresh new install, and ran into a lot of errors while following the instructions to train a Connect4 agent after what looked like a successful precompilation.
Replacing Julia with version 1.6.7 solved the errors.

**Comment by jonathan-laurent** [comment]
The dev version works on 1.8.4 but not the latest release indeed.
I just made a new release. Please tell me if it solves your problem.

**Comment by smart-fr** [comment]
AlphaZero.jl release 0.5.4 solved my problem. Thank you!
