### ISSUE TITLE
Missing repository's website

### ISSUE THREAD

**Issue by zdroid** [jonathan-laurent/AlphaZero.jl#16]
It seems this repository is missing a website link.
https://jonathan-laurent.github.io/AlphaZero.jl/stable/ or https://jonathan-laurent.github.io/AlphaZero.jl/dev/ are suitable candidates for that.

It should be here:
![Screenshot from 2020-06-24 01-58-09](https://user-images.githubusercontent.com/2725611/85479312-31ac2380-b5be-11ea-98d8-0425fd8cf6f8.png)

**Comment by jonathan-laurent** [comment]
This is a great suggestion, which I just implemented.
Thanks!

**Comment by zdroid** [comment]
@jonathan-laurent Another suggestion, while we're here. You can add tags in the same place, which will help the repo to be found more easily.
