### ISSUE TITLE
Training Stuck at 'Network Only against MinMax (depth 6)' after Modifying TicTacToe Board Size to 4x4

### ISSUE THREAD

**Issue by solidcub** [jonathan-laurent/AlphaZero.jl#180]
Hello, thank you so much for creating such an amazing project. I recently started using GitHub because of this project. I am currently studying the Connect-4 and TicTacToe code to train my game using AlphaZero.

As a first step, I modified the const BOARD_SIDE = 3 in TicTacToe's game.jl to const BOARD_SIDE = 4 and created a new game name for learning.

julia --project -e 'using AlphaZero; Scripts.explore("new-game")'

The game tests on a 4x4 board run fine.

julia --project -e 'using AlphaZero; Scripts.train("new-game")'

However, when I try to train using the above command:

Running benchmark: AlphaZero against MCTS (400 rollouts)

It works fine up to 100%.

Running benchmark: Network Only against MinMax (depth 6)

After printing the above message, the process stops.

I am unsure about the cause of this issue and would like to ask for guidance on how to proceed. I apologize for the basic question and appreciate the well-organized code that is great for learning. I am looking forward to your response.

![new_game](https://user-images.githubusercontent.com/108007233/231613120-ce51ec30-242e-4234-a6c4-bbf69f89cd92.png)

**Comment by jonathan-laurent** [comment]
Thanks for reaching out! I suspect you are using too much depth for your minmax baseline. For standard tictactoe, the branching factor is really small so exhaustive exloration at depth 6 can work. However, if you enlarge the grid to $4 \times 4$, depth 6 means visiting $16 \times 15 \times 14 \times 13 \times 12 \times 11 \approx 6 \times 10^6$ nodes from the root, which is probably too expensive.

**Comment by solidcub** [comment]
I adjusted the MinMaxTS depth from 6 to 4 in params.jl, and now everything works as expected.

I have two more questions:

If I purchase an RTX 4090, can I fully utilize its performance for training with AlphaZero.jl? Also, I assume it's not possible to train using a MacBook Pro with an M2 processor, correct?
Would it be possible to use the parameters learned with AlphaZero.jl in an indie game I plan to develop in the future?
I'm still learning, but I hope to contribute to this project in the future as my knowledge grows.

Many thanks!

![ttt4](https://user-images.githubusercontent.com/108007233/231726935-c343d8e2-969f-4ad4-8a01-5fdb1d071643.png)
