### ISSUE TITLE
What next after training an agent?

### ISSUE THREAD

**Issue by pepa65** [jonathan-laurent/AlphaZero.jl#187]
I followed the readme in training an agent, except I chose `tictactoe` (as `connect-four` ran out of memory), and it completed!

What can I now do to use the result?

**Comment by jonathan-laurent** [comment]
You can do anything you want with the trained network weights.
If you just want to play against the agent or visualize MCTS stats, you can use the `explore` and `play` [scripts](https://jonathan-laurent.github.io/AlphaZero.jl/stable/reference/scripts/).

**Comment by pepa65** [comment]
OK, this works: `julia --project -e 'using AlphaZero; Scripts.play("mancala")'`
