### ISSUE TITLE
using AlphaZero 

### ISSUE THREAD

**Issue by MHiero** [jonathan-laurent/AlphaZero.jl#19]
Hallo Jonathan,
thanks for this great project. 
I would like to dive deeper into it, but I have a problem with the Pkg...

julia> import Pkg; Pkg.add("AlphaZero")
   Updating registry at `C:\Users\H\.juliapro\JuliaPro_v1.4.2-1\registries\JuliaPro`
ERROR: The following package names could not be resolved:
 * AlphaZero (not found in project, manifest or registry)

Do you have any helping advice?

**Comment by jonathan-laurent** [comment]
Hi MHiero,
AlphaZero.jl is not registered in the general package repository yet (it will be soon when I publish the v0.4 release)
You will have to clone the repo and instantiate the project yourself, as specified in the README.

**Comment by MHiero** [comment]
Thank you very much for the fast reply. I found out that my path variable had an error. Now it works :)

Maybe we can add in the tutorial:
To download AlphaZero.jl and start a new training session, just run the following in a shell (with the path variable set to Julia.exe):

Best regards.
MH
