### ISSUE TITLE
Any way to start when playing against AlphaZero?

### ISSUE THREAD

**Issue by pepa65** [jonathan-laurent/AlphaZero.jl#192]
Maybe this is just not possible because of how it was trained, but I play Connect Four like this: `julia --project -e 'using AlphaZero; Scripts.play("connect-four")'` (and getting crushed all the time...). Would there be any way for me to start the game??

**Comment by 70Gage70** [comment]
This is what worked for me with tictactoe. Assuming you already trained trained with the default values:

```julia
experiment = Examples.experiments["tictactoe"]
session = Session(experiment, dir = "sessions/tictactoe/")
 ```
 
 Then, this command allows you to make the first move:
 
 ```julia
 interactive!(session.env.gspec, Human(), AlphaZeroPlayer(session))
 ```

**Comment by pepa65** [comment]
Thank you, this works: `julia --project -e 'using AlphaZero; experiment = Examples.experiments["connect-four"]; session = Session(experiment, dir = "sessions/connect-four/"); interactive!(session.env.gspec, Human(), AlphaZeroPlayer(session))'`
