### ISSUE TITLE
supervised learning

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#210]
May I expect a supervised learning in AlphaZero.Jl project?
Reinforcement learning with self-playing takes an incredible amount of time, but I have a database of the players, so I'd like to use it to speed up the process.

Thank you.

**Comment by jonathan-laurent** [comment]
This is not planned in the short term but I would be interested in a contribution of this kind (providing utilities to bootstrap an initial policy via supervised learning).
