### ISSUE TITLE
Generic POMDP Support

### ISSUE THREAD

**Issue by nateybear** [jonathan-laurent/AlphaZero.jl#212]
Hello! Apologies if this has been asked elsewhere. 

I remember seeing that a goal for AlphaZero.jl is to support any class of POMDP. Is there any update as to the status of that milestone? As an end user this would be a huge deal for me, though I’m not familiar enough with the ecosystem and research to implement it myself at this point. 

Some useful features: multi-agent games, incomplete information, and continuous (or mixed discrete-continuous) action spaces.

Any insight on plans for these things or implementations in other package ecosystems would be much appreciated!

**Comment by jonathan-laurent** [comment]
Supporting general POMDPs is not a short-term goal for AlphaZero.jl
Dealing with multiplayer games and imperfect information requires pretty different algorithms and AlphaZero would be a bad fit in many/most cases. You may find some discussion about this in other issues.
