### ISSUE TITLE
Which hardware is recommended for non-trivial games?

### ISSUE THREAD

**Issue by StepHaze** [jonathan-laurent/AlphaZero.jl#214]
Please write minimal hardware configuration for non-trivial games like chess, checkers and go? (cluster of GPUs?)
Does AlphaZero.jl support parallel computing?

**Comment by jonathan-laurent** [comment]
Chess, checkers and go are too complex to be solved naively on a single GPU. It might be possible to use AlphaZero on those games and with a single GPU by providing a good initial policy (e.g learned via supervised learning) but this is an open question. As asked in other issues, AlphaZero.jl can currently run on a cluster, although it can only leverage a limited amount of parallelism (only the data generation step is parallelized and not the evaluation, so it might not scale well beyond 4-9 machines).
