### ISSUE TITLE
Error building `Knet`

### ISSUE THREAD

**Issue by drozzy** [jonathan-laurent/AlphaZero.jl#22]
Tried installing this on Ubuntu 20.04, Julia 1.5.2, and got this error after calling `julia --project -e "import Pkg; Pkg.instantiate()"`:
```
Error: Error building `Knet`: 
│ In file included from /usr/local/cuda-10.1/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
│                  from <command-line>:
│ /usr/local/cuda-10.1/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
│   138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
│       |  ^~~~~
│ [ Info: cuda1.jl
│ [ Info: `/usr/local/cuda-10.1/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options '-O3 -Wall -fPIC' -c cuda1.cu`
│ ERROR: LoadError: failed process: Process(`/usr/local/cuda-10.1/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options '-O3 -Wall -fPIC' -c cuda1.cu`, ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run at ./process.jl:438 [inlined]
│  [4] inforun(::Cmd) at /home/andriy/.julia/packages/Knet/bTNMd/deps/build.jl:9
│  [5] build_nvcc() at /home/andriy/.julia/packages/Knet/bTNMd/deps/build.jl:75
│  [6] build() at /home/andriy/.julia/packages/Knet/bTNMd/deps/build.jl:87
│  [7] top-level scope at /home/andriy/.julia/packages/Knet/bTNMd/deps/build.jl:93
│  [8] include(::String) at ./client.jl:457
│  [9] top-level scope at none:5
│ in expression starting at /home/andriy/.julia/packages/Knet/bTNMd/deps/build.jl:93

```

**Comment by jonathan-laurent** [comment]
Unfortunately, it is not the first time I am seeing people having problems building Knet.
I suggest that you post an issue [here](https://github.com/denizyuret/Knet.jl/issues).

In the near future, I should be able to make Knet an optional dependency for AlphaZero.jl and so people will be able to use it with Flux only.

**Comment by denizyuret** [comment]
@drozzy I would like to help. What version of Knet are you using? Knet has not needed nvcc or a working CUDA toolkit for a while now. It should work out of the box as long as CUDA.jl works. There is no building process.

@jonathan-laurent please forward any installation issues to me.

**Comment by denizyuret** [comment]
@jonathan-laurent -- I think the issue is your latest released Manifest.toml file points to Knet-1.3.5 which requires a working CUDA toolkit and compiler to build. After CUDA.jl started shipping with its own libraries we dropped this requirement and the later Knet versions (definitely after 1.4.0) do not have this requirement and should be backward compatible with your code.

**Comment by jonathan-laurent** [comment]
@denizyuret Good catch! I will update the Manifest.

**Comment by drozzy** [comment]
> @drozzy I would like to help. What version of Knet are you using? Knet has not needed nvcc or a working CUDA toolkit for a while now. It should work out of the box as long as CUDA.jl works. There is no building process.
> 
> @jonathan-laurent please forward any installation issues to me.

How do I check? Sorry, I'm new to Julia. I assume whatever is in this dependency file?
https://github.com/jonathan-laurent/AlphaZero.jl/blob/master/Project.toml

**Comment by jonathan-laurent** [comment]
To check the version of a package, you can open the REPL with `julia --project` and then type `]status`.
Then, you can try and update Knet to the latest version by typing `]update Knet`.

Note: I will be releasing AlphaZero.jl v0.4 in a few days, with many new exciting features.

**Comment by drozzy** [comment]
```
Project AlphaZero v0.3.0
Status `~/Projects/AlphaZero.jl/Project.toml`
  [c7e460c6] ArgParse v1.1.0
  [052768ef] CUDA v0.1.0
  [35d6a980] ColorSchemes v3.9.0
  [5ae59095] Colors v0.12.3
  [a8cc5b0e] Crayons v4.0.3
  [864edb3b] DataStructures v0.17.19
  [31c24e10] Distributions v0.23.4
  [e30172f5] Documenter v0.25.0
  [587475ba] Flux v0.11.0-DEV `https://github.com/FluxML/Flux.jl.git#master`
  [59287772] Formatting v0.4.1
  [d9f16b24] Functors v0.1.0
  [2535ab7d] JSON2 v0.3.2
  [0f8b85d8] JSON3 v1.0.3
  [1902f260] Knet v1.3.5
  [91a5bcdd] Plots v1.5.0
  [92933f4c] ProgressMeter v1.3.1
  [90137ffa] StaticArrays v0.12.3
  [e88e6eb3] Zygote v0.4.22
  [9a3f8284] Random
  [9e88b42a] Serialization
  [10745b16] Statistics
```
So it's at 1.3.5, i just did update and I think it tried to update it to 1.3.7:
```
┌ Error: Error building `Knet`: 
│ ERROR: LoadError: LoadError: LoadError: UndefVarError: AddrSpacePtr not defined
│ Stacktrace:
│  [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
│  [2] top-level scope at /home/andriy/.julia/packages/CUDA/5t6R9/src/device/cuda/wmma.jl:52
│  [3] include(::Function, ::Module, ::String) at ./Base.jl:380
│  [4] include at ./Base.jl:368 [inlined]
│  [5] include(::String) at /home/andriy/.julia/packages/CUDA/5t6R9/src/CUDA.jl:1
│  [6] top-level scope at /home/andriy/.julia/packages/CUDA/5t6R9/src/device/cuda.jl:15
│  [7] include(::Function, ::Module, ::String) at ./Base.jl:380
│  [8] include at ./Base.jl:368 [inlined]
│  [9] include(::String) at /home/andriy/.julia/packages/CUDA/5t6R9/src/CUDA.jl:1
│  [10] top-level scope at /home/andriy/.julia/packages/CUDA/5t6R9/src/CUDA.jl:39
│  [11] include(::Function, ::Module, ::String) at ./Base.jl:380
│  [12] include(::Module, ::String) at ./Base.jl:368
│  [13] top-level scope at none:2
│  [14] eval at ./boot.jl:331 [inlined]
│  [15] eval(::Expr) at ./client.jl:467
│  [16] top-level scope at ./none:3
│ in expression starting at /home/andriy/.julia/packages/CUDA/5t6R9/src/device/cuda/wmma.jl:52
│ in expression starting at /home/andriy/.julia/packages/CUDA/5t6R9/src/device/cuda.jl:14
│ in expression starting at /home/andriy/.julia/packages/CUDA/5t6R9/src/CUDA.jl:39
│ ERROR: LoadError: Failed to precompile CUDA [052768ef-5323-5732-b1bb-66c8b64840ba] to /home/andriy/.julia/compiled/v1.5/CUDA/oWw5k_EFn4P.ji.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
│  [3] _require(::Base.PkgId) at ./loading.jl:1030
│  [4] require(::Base.PkgId) at ./loading.jl:928
│  [5] require(::Module, ::Symbol) at ./loading.jl:923
│  [6] include(::String) at ./client.jl:457
│  [7] top-level scope at none:5
│ in expression starting at /home/andriy/.julia/packages/Knet/V526D/deps/build.jl:1
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

**Comment by drozzy** [comment]
Ok, I just switched to master, and it works (it uses knet 1.4.1)!!! Nice.

Perhaps you should replace this instruction on the front page readme with a master instead (since this version uses old knet)?
```
git clone --branch v0.3.0 https://github.com/jonathan-laurent/AlphaZero.jl.git
```

**Comment by jonathan-laurent** [comment]
This is good to hear!
I am unsure about encouraging people to use #master by default as the documentation is not always up-to-date on master.
But I should definitely document this possibility on the README.

Also, my intention is to register AlphaZero.jl for its v0.4 release.
Then, it should become possible to install AlphaZero by simply typing `]add AlphaZero` or `]add AlphaZero#master`in a Julia REPL.
