### ISSUE TITLE
Connect Four iteration training time is taking a long time

### ISSUE THREAD

**Issue by furianz** [jonathan-laurent/AlphaZero.jl#31]
I’ve downloaded the codebase from github (v0.3) and have gone thru the instructions to run the sample, but I am getting iteration times that are substantially longer than what is mentioned in the documentation (8 – 16 hrs / iteration vs 30-50 minutes).  I am wondering if I don’t have something set correctly on my system or with the Julia environment.    See screen cap below which shows 4% with an ETA of 16 hrs and 37 minutes.  System I have is reasonably capable but even on a higher end system (64 gig ram, rtx 2080 super) still getting much slower results.

![image](https://user-images.githubusercontent.com/76178519/103643845-f601f700-4f1a-11eb-9eb8-c83674299ac1.png)

Thoughts on the problem?  Thank you.

**Comment by jonathan-laurent** [comment]
From the nvidia-smi screenshot you sent me by email, it looks like AlphaZero.jl is not using your GPU here, which explains why training is so slow.

Would you mind running the Knet [tests](https://denizyuret.github.io/Knet.jl/latest/install/) and share the output with me?
```julia
using Knet; include(Knet.dir("test/gpu.jl"))
```

**Comment by jonathan-laurent** [comment]
This is strange. Your Knet installation appears to be working but your GPU is clearly not used when running AlphaZero.jl.
Would you be able to run the version on master with the Flux backend?
To do so, you should set the `ALPHAZERO_DEFAULT_DL_FRAMEWORK` env variable to `FLUX` (see `src/AlphaZero.jl`).

**Comment by furianz** [comment]
Jonathan, I ended up re-installing everything and did the following:
- Installed Julia Pro 1.5.3
- cloned the master branch of AlphaZero.jl
- cd AlphaZero.jl
- julia --project -e "import Pkg; Pkg.instantiate(verbose=true)"
- julia --project --color=yes scripts/alphazero.jl --game connect-four train
initial results were better but getting 2+ hours for the training iteration on high end laptop (64 gig RAM, rtx 2080 super)

![image](https://user-images.githubusercontent.com/76178519/103949195-83eb0700-5100-11eb-8709-4ff5100283d1.png)

![image](https://user-images.githubusercontent.com/76178519/103949222-8cdbd880-5100-11eb-8163-2c5220440f64.png)

Switching over to Flux got initial similar type of result, didn't wait for iteration to complete

![image](https://user-images.githubusercontent.com/76178519/103949325-b432a580-5100-11eb-9ac8-b1c0adec8df6.png)

Thoughts?  Thank you.

**Comment by jonathan-laurent** [comment]
Ok, so this is still much better than what you had before (~2h vs ~16h) and your GPU seems to be working now, but I agree the performances are still somewhat disappointing. Two things to keep in mind:

- My comment in the documentation that each iteration should take about an hour is about v0.3, where the connect-four example uses different hyper-parameters. With the hyperparameters in master, you should be able to learn a great player in about 10-15 iterations so the performances you have here should not be a deal breaker.
- I have observed performance regressions recently as I updated my Julia ecosystem and I am still trying to figure out where it comes from. I will keep you updated about this.

**Comment by furianz** [comment]
Thanks for the feedback, and definitely let me know what you find out.  I am going to take a stab at adding my own game!

**Comment by magicly** [comment]
@furianz @jonathan-laurent I think SelfPlayParams.num_games=5000 is too high, setting it to 500 works fine, and much faster. It takes about 8min per iteration.

**Comment by jonathan-laurent** [comment]
@magicly Interesting. With 500 games per iteration, how many iterations does it take to beat the baselines with the neural network alone though? If I play 5000 games per iteration, ~10 iterations are about enough for the neural network alone to win about ~80% of ts game against MCTS. (That being said, I agree that this parameter is probably set too high right now. One reason I set it so high is that it  currently enables better gains when running AlphaZero.jl in a distributed way as only the self-play part is parallelized right now.)

@furianz I tried running the common-rl-intf branch on Julia 1.6-beta and the initial self-play sequence takes ~1h again, which is much better.

**Comment by jonathan-laurent** [comment]
@furianz I encourage you to try and run the connect four example again on master with Julia 1.6-rc1.
I am getting pretty good performances now.

**Comment by magicly** [comment]
@jonathan-laurent sorry for replying so late.  With 500 games per iteration and nothing else changed, ~70 iterations are about enough for the neural network alone to win about ~80% of ts game against MCTS.  I think there is still room for improving, I'm working on it.  I will post another issue after some analysis.

**Comment by jonathan-laurent** [comment]
@magicly Thanks for investigating. Please do not hesitate to share your hyperparameters when you are done!
