### ISSUE TITLE
Question about function test_symmetry

### ISSUE THREAD

**Issue by smart-fr** [jonathan-laurent/AlphaZero.jl#33]
Hello Jonathan,
Could you please explain in a few words what the function [test_symmetry(Game, state, (symstate, aperm)) in game.jl](https://github.com/jonathan-laurent/AlphaZero.jl/blob/master/src/game.jl#L169) tries to do?
I'm quite new to Julia, and I must confess I have a hard time making sure what it does.
Currently it's where test_game fails on my game.
Thank you!

**Comment by jonathan-laurent** [comment]
Can you send me a Github link to the code? I am not sure what version of the code you are referring to.

**Comment by smart-fr** [comment]
Sure! I edited the original question with the link. (https://github.com/jonathan-laurent/AlphaZero.jl/blob/master/src/game.jl#L169)

**Comment by jonathan-laurent** [comment]
Intuitively, it checks that a given symmetry `(symstate, aperm)` is valid in state `state` by doing the following sanity check.

**Sanity check:** There are two ways to compute the set of all valid actions for state `symstate` and these two ways must coincide:

1. Call `actions_mask` on `symstate` directly.
2. Call `actions_mask` on `state` and transform it using the `aperm` permutation.

**Comment by smart-fr** [comment]
Clear, thank you.
Then ach! Shouldn't the answer to [issue 32](https://github.com/jonathan-laurent/AlphaZero.jl/issues/32) be
neither
1. actions_mask2[action_index] == actions_mask1[σ(action_index)]
nor
2. actions_mask2[σ(action_index)] == actions_mask1[action_index]
but
3. actions_mask2[action_index] == σ(actions_mask1[action_index])
?

**Comment by jonathan-laurent** [comment]
Now that I look closer, your expressions do not appear to be type-correct.

`actions_mask1[action_index]` should be a boolean and `σ` is an array if integers describing a permutation.

Would you mind reformulating your question accordingly?

**Comment by smart-fr** [comment]
My bad -my last question and proposition 3. are indeed incorrect.
I think your answer to [issue 32](https://github.com/jonathan-laurent/AlphaZero.jl/issues/32) is consistent with your description of `test_symmetry` here: calling `actions_mask` on `state` and transforming it using the `aperm` permutation means `actions_mask2[action_index] == actions_mask1[σ(action_index)]` in issue 32.
I have to understand why my implementation fails the symmetry sanity check. ;-)
