### ISSUE TITLE
How to use AlphaZero.jl for Openspiel games?

### ISSUE THREAD

**Issue by SwiftGodDev** [jonathan-laurent/AlphaZero.jl#46]
How can I use Alphazero.jl for RL in openspiel games?

**Comment by jonathan-laurent** [comment]
Thanks for your interest in AlphaZero.jl.

I haven't implemented direct support for Openspiel yet but it should be pretty easy to do. In fact, I was thinking of leaving it as a project for first-time contributors.

There is a Julia wrapper for Openspiel that can be found [here](https://github.com/JuliaReinforcementLearning/OpenSpiel.jl). All there is to do is to wrap an openspiel environment in such a way to implement [GameInterface](https://jonathan-laurent.github.io/AlphaZero.jl/dev/reference/game_interface/). I already did this [here](https://github.com/jonathan-laurent/AlphaZero.jl/blob/master/src/common_rl_intf.jl) for the CommonRLInterface.jl package and so the latter can be used as an example.

I would welcome a PR here if you are interested in adding support for OpenSpiel. Alternatively, I can have myself or a student work on it in the next two weeks or so.

**Comment by SwiftGodDev** [comment]
Actually I would leave this to you because I have no idea of julia. You can write it in a better way than me as you have more experience in julia.

**Comment by jonathan-laurent** [comment]
@michelangelo21 just contributed an OpenSpiel.jl wrapper for AlphaZero.jl along with a tic-tact-toe example.
I am closing this issue but please don't hesitate to reopen it if you have questions or encounter some rough edges!
