### ISSUE TITLE
MCTS Optimization for sparse actions

### ISSUE THREAD

**Issue by blacksph3re** [jonathan-laurent/AlphaZero.jl#49]
Currently it seems to me that per MCTS node, a vector of length action encoding is saved, holding Q values, NN probs and edge visits. However for some games this is suboptimal. Let's take tak or the slightly less famous chess.
In chess, you need a vector of length >4k to onehot encode actions. However the branching factor is 31. In Tak on the 5x5 board the encoding lenght is >2k with a branching factor of ca 60. Means only a fraction of the actions for each given state are actually possible to take. With tak this has the consequence that I am swapping quite a bit on my machine. It would save quite some memory if some sparse storage can be used for these games.

Now I see two implementation Options. The one is straightforward, just replace the vector with a sparsevector and it needs almost no code change. This could probably reuse the code and just take an extra parameter in the initialization. The second option is to use a non-sparse vector of length `sum(action-mask(state))`. The ith element in the vector corresponds to the ith element in `findall(action-mask(state))`. This has a slight computational plus, especially if generating the action mask isn't trivial for a state, but saves even the indexing vector.

What are your thoughts on this? If you are to rewrite the MCTS anyway maybe you could take this into consideration?

**Comment by jonathan-laurent** [comment]
Your second suggestion is in fact what is currently implemented: the MCTS tree stores Q-values in a vector of size `available_actions(state)`. The same holds for the memory buffer.

However, the neural network outputs a vector of size the total number of actions and this can be a problem in environments with very "sparse" action sets. Although it is still reasonable to have a network with ~2k output neurons in the case of Chess, we can imagine environments with relatively low branching factors but literally infinite action spaces. See also [this comment](https://github.com/jonathan-laurent/AlphaZero.jl/issues/38#issuecomment-797694871).

**Comment by blacksph3re** [comment]
Ah okay then I misunderstood the implementation! Thanks for clarifying, I will memory optimize elsewhere
