### ISSUE TITLE
Use Base.Logging and ProgressLogging

### ISSUE THREAD

**Issue by jonathan-laurent** [jonathan-laurent/AlphaZero.jl#55]
Right now, a lot of the code uses custom logging solutions.

We should use Base.Logging.jl and ProgressLogging.jl instead. This would make the code simpler and allow custom logging backends other than ANSI terminals (e.g. JuliaHub).

**Comment by jonathan-laurent** [comment]
There is nothing that keeps you from using the default logger within your main function indeed (using `@warn`, `@info`...).
You may want to define a custom handler though so as to avoid polluting the UI terminal output.

**Comment by gwario** [comment]
Yeah, ok. But i thought it would be nice to have it in the sessions/<game>/log.txt and i think it would be a bad idea to let the base logging alao write to this file along with the alphazero session logger.
My idea was to somehow access the session from the game, but i could figure out how to do it. What would you say is the proper way to do that?

**Comment by jonathan-laurent** [comment]
I think what you want to do can be done by using `@warn` and `@info` normally within your game (with a special tag in the payload), but then define a handler at the session level that intercepts these messages and does whatever you want with them.

I believe this is one of the great features of Julia's logging system: you can cleanly separate emitting logging messages and processing them. Accessing the session from the game implementation would not be a good practice from a software engineering perspective as it introduces some artificial coupling in your codebase for little benefit.

**Comment by gwario** [comment]
> I think what you want to do can be done by using `@warn` and `@info` normally within your game (with a special tag in the payload), but then define a handler at the session level that intercepts these messages and does whatever you want with them.

Hmm now i think i understand what you mean.. I'll try to figure it out..
> 
> I believe this is one of the great features of Julia's logging system: you can cleanly separate emitting logging messages and processing them. Accessing the session from the game implementation would not be a good practice from a software engineering perspective as it introduces some artificial coupling in your codebase for little benefit.

True, didn't think of that...

Thanks for the pointers thus far!

**Comment by jonathan-laurent** [comment]
This will be tackled in the redesign.
