### ISSUE TITLE
Performance Docs

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#58]
You should really update the docs and example launch commands to explain to people the proper settings to get the most performance.
Specifically
using -t <V_cpus>
and
adjusting batchsize to get the most gpu usage possible

**Comment by jonathan-laurent** [comment]
This is a good suggestion.
I think using -t <V_cpus> is not necessary with Julia 1.6+ as it uses as many threads as there are CPU available by default.
But you are right I could tell something about modifying batch size.

By the way, if you find something missing in the doc, don't hesitate to have a go at adding it yourself and submit a PR!

**Comment by SheldonCurtiss** [comment]
Ok once I wrap my head around this and manage to fully train I will :)
