### ISSUE TITLE
 isprobvec(p) error?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#59]
![image](https://user-images.githubusercontent.com/78921582/129444472-c2a26dd0-1954-419f-bfe8-ef9505fe2863.png)

Any idea what's causing this?

**Comment by jonathan-laurent** [comment]
It is hard for me to tell without more context.
This means that the action prior returned by the network is not a valid probability vector and you should add some print statements in the code to learn more about it.

**Comment by SheldonCurtiss** [comment]
> It is hard for me to tell without more context.
> This means that the action prior returned by the network is not a valid probability vector and you should add some print statements in the code to learn more about it.

I just recalled how I fixed it previously I think.
Pretty sure it was due to me running 1.6 as opposed to 1.6.2.

Will report back. Should I be using Beta as per your suggestion in an issue a month or so back?

**Comment by jonathan-laurent** [comment]
I recommend using the latest Julia release, so 1.6.2 in this case.

**Comment by SheldonCurtiss** [comment]
Using 1.6.2 I'm still getting the issue.
I swear I had it working previously. I've testing multiple different things and am unsure the cause still.

Could this in anyway be due to the way I'm vectorizing state?

**Comment by jonathan-laurent** [comment]
You should just add a conditional statement in the code making this `isprobvec` check and printing the faulty vector when the check fails so that we can figure out what's going on here. It could simply be an issue of numerical imprecision.

**Comment by SheldonCurtiss** [comment]
Gonna be honest I have 0 idea where to even place that given this error message.
Do you have any guesses what could be causing this?


  Running benchmark: Network Only against MCTS (60 rollouts)

ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.
Stacktrace:
 [1] ArgumentError: macro expansionCategorical: the condition isprobvec(p) is not satisfied.

Stacktrace:

Stacktrace:
 [1]
Stacktrace:
macro expansion [1]
   @
Stacktrace:
~/.julia/packages/Distributions/Xrm9e/src/macro expansion
   @ utils.jl:6~/.julia/packages/Distributions/Xrm9e/src/
Stacktrace: [inlined]


Stacktrace:   @

Stacktrace:~/.julia/packages/Distributions/Xrm9e/src/
 [1]  [1]macro expansion
   @
Stacktrace:
macro expansion~/.julia/packages/Distributions/Xrm9e/src/
utils.jl   @ :6~/.julia/packages/Distributions/Xrm9e/src/  [inlined][1]
  [2]macro expansion
   @ ~/.julia/packages/Distributions/Xrm9e/src/ #_#37utils.jl:
   @ 6~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined] [1]
ArgumentError:  macro expansionCategorical: the condition isprobvec(p) is not satisfied.
   @ ~/.julia/packages/Distributions/Xrm9e/src/utils.jl:6 [inlined] [2]
 utils.jl#_#37
:   @ 6~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined] [1]

Stacktrace:macro expansion

   @ ~/.julia/packages/Distributions/Xrm9e/src/ [1]  [2]macro expansion
   @  ~/.julia/packages/Distributions/Xrm9e/src/#_#37categorical.jl:
   @ 30~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined] [2]
 categorical.jl:#_#37
30   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:30 [inlined] [1]
 categorical.jl:macro expansion30
   @ ~/.julia/packages/Distributions/Xrm9e/src/  [inlined][3]
 utils.jl#Categorical#38:
6   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]
utils.jl:6 [inlined]
categorical.jl:34  [inlined][3]
  [2]#Categorical#38
   @   ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/[2]#_#37
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/  #_#37[3]
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ #Categorical#38utils.jl
:6   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:34  [inlined][3]
  [4]#Categorical#38
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/  [2]DiscreteNonParametric
     @ [2]#_#37~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ categorical.jl#_#37:
30   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:34  [inlined][4]
 categorical.jlDiscreteNonParametric:
34   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:30 [inlined] [3]
 categorical.jl#Categorical#38:
34   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/  [inlined][4]
  [3]DiscreteNonParametric
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ categorical.jl:#Categorical#3834
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]
utils.jl:6 [inlined] [5]
 categorical.jl:34rand_categorical(π:: [inlined]categorical.jl
:30 [inlined]
categorical.jl:34 [inlined]categorical.jl
:30  [inlined][3]
  [5]#Categorical#38
   @  ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [3]rand_categorical(π::  #Categorical#38[2]
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ categorical.jl:#_#3734
   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]
categorical.jl:30 [inlined]categorical.jl
:34  [inlined][5]
  [4]rand_categorical(π categorical.jl::DiscreteNonParametric:
34   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:34  [inlined]
[4]ArgumentError:  Categorical: the condition isprobvec(p) is not satisfied.DiscreteNonParametric
   @  [4]~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/  [5]DiscreteNonParametric
   @   [4]rand_categorical~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/(  [4]DiscreteNonParametric πcategorical.jl::
DiscreteNonParametric:
   @ 34~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/   @ ~/.julia/packages/Distributions/Xrm9e/src/univariate/discrete/ [inlined]categorical.jl
:34 [inlined]
categorical.jl:34 [inlined] [5]
  [5]rand_categorical (rand_categoricalcategorical.jl(π:π::::34 [inlined] [5]
  [5]rand_categorical( πArgumentError: ::rand_categorical(Categorical: the condition isprobvec(p) is not satisfied.π::Stacktrace:
 [1] ArgumentError: macro expansionCategorical: the condition isprobvec(p) is not satisfied.

**Comment by SheldonCurtiss** [comment]
-___-
![image](https://user-images.githubusercontent.com/78921582/129451548-0c4e6472-9f0d-469b-a1de-e40cd6504111.png)
Fixed it.
The cause of the issue was having reward 0. if both black and whites scores matched. Changing to -1. resolved this.
Though now I'm getting whatever this means?

**Comment by SheldonCurtiss** [comment]
Google says something regarding additional dependencies required?

**Comment by SheldonCurtiss** [comment]
Think that also fixed it. This is such a headache. I solved this previously too but have been fighting with everything in an attempt to squeeze out all possible CPU and GPU power that is without crashing Nvidia drivers.
zzz

Anyhow I have this all in my notes so I shouldn't run into it again.

Dependencies can be found here: https://gr-framework.org/julia.html#installation

Still would love your input as to why 0. on black white score == was causing this

**Comment by SheldonCurtiss** [comment]
Ok. So. The issue just came back again...
I had done something like 20 attempts and got the error.
I changed reward 0. when both black and whites scores are equal to -1.

I then changed batch size up from 2048 > 3072 and the issue is back...

**Comment by SheldonCurtiss** [comment]
![image](https://user-images.githubusercontent.com/78921582/129452521-75f0501d-cdad-4287-a9c3-dfa92b202025.png)
Ok so reverting the batch size and game changes / number of iters seems to of fixed it again???
Or am I just getting lucky again?

**Comment by SheldonCurtiss** [comment]
![image](https://user-images.githubusercontent.com/78921582/129453383-fd44432b-e18f-4a3d-ae59-8bc08d10c579.png)
Seems it's random. Ok cool.

**Comment by SheldonCurtiss** [comment]
I was able to resolve this issue by disabling the network only benchmark.
