### ISSUE TITLE
Do these readout look correct?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#60]
![image](https://user-images.githubusercontent.com/78921582/129490811-98592b7c-614d-4c9f-b4a2-36c543a9f5e7.png)

Just started training, does this look right for first iterations?
Also any idea what the connection reset by peer stuff is?

**Comment by jonathan-laurent** [comment]
It looks like it is learning something here indeed.

The Broken pipe stuff is a well known GR bug, which you can probably eliminate by running the following before you launch Julia:

```sh
export GKSwstype=100  # To avoid an occasional GR bug
```

**Comment by SheldonCurtiss** [comment]
Pretty positive I ran that but I'll run it again to be safe, will that cause any issues?

As for the training when it says 'launching a checkpoint evaluation' what exactly is the reward based on? The network vs what?

**Comment by jonathan-laurent** [comment]
> Pretty positive I ran that but I'll run it again to be safe, will that cause any issues?
No.

> As for the training when it says 'launching a checkpoint evaluation' what exactly is the reward based on? The network vs what?
For two-player games: it is the current network vs the best one seen so far.
For one-player games, the player plays several games and the average reward is collected.

**Comment by SheldonCurtiss** [comment]
Awesome - I think this might just actually be working finally hype!
Unsure if you saw my solution to that other error I was getting - I disabled network only benchmarks and am only using the full benchmark (alphazero + mcst???)

What exactly is taking place during 'alphazero vs mcst'? I read the documentation multiple times and still don't follow.
