### ISSUE TITLE
Benchmark Questions?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#61]
The documentation seems a bit slim on these:
AlphaZero.Benchmark.Full
Full AlphaZero player that combines MCTS with the learnt network.
Argument params has type MctsParams.

AlphaZero.Benchmark.NetworkOnly
Player that uses the policy output by the learnt network directly, instead of relying on MCTS.

What exactly is 'AlphaZero.Benchmark.Full'? and what the the purpose of 'Running benchmark: AlphaZero against MCTS'

Is there any way to just have two players compete against each other directly for this benchmark?

**Comment by jonathan-laurent** [comment]
Honestly, your best reference for all of these is to just look at the source, which is pretty simple.
Don't hesitate to submit PRs to improve the documentation though.

Full means MCTS+Network: the full AlphaZero player.

To get two players playign against each other, you probably want a `Duel` between two `Full` players.

**Comment by SheldonCurtiss** [comment]
But wouldn't it be better to do NetworkOnly vs Network only? or Network only vs full?
My game isn't predictable thus MCST wouldn't be very fair.
When I do network only vs network only things appear to break.
