### ISSUE TITLE
Does Scripts.play("connect-four") cheat?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#62]
I'm attempting to add the ability to test my trained AI, I tried out Scripts.play("connect-four") mind you I have no sessions that exist for connect-four and haven't done any training for connect-four but when playing against the agent it was playing incredibly well.

Does Scripts.play cheat in any way? If so what's the best way to test an agent without this?

**Comment by jonathan-laurent** [comment]
Even with a random (untrained) heuristic, MCTS is already decent at connect four so this is not too surprising.
But no cheating!

**Comment by SheldonCurtiss** [comment]
Got it thanks!
