### ISSUE TITLE
isprobvec(p) whenever using Benchmark.NetworkOnly(τ=0.5)

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#63]
Any suggestions as to why this would be happening?

**Comment by jonathan-laurent** [comment]
The best way to debug this is to look at your error stack trace, inspect the source code and put print statements near the error location.

**Comment by SheldonCurtiss** [comment]
Why is julia like every other language I've used and the error messages are next to uselss?
I assume you've never seen this before - I'm digging now

**Comment by SheldonCurtiss** [comment]
@jonathan-laurent I'm still locating the error
separate from this is it possible to have two network players?
