### ISSUE TITLE
How exactly does Alphazero's MCTS work?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#64]
Is it directly simulating future boards or is it simulating predicted future boards if that makes sense?

My understanding is it's directly simulating future boards is that correct?

**Comment by jonathan-laurent** [comment]
The question is too vague to answer precisely.
AlphaZero's MCTS uses a perfect simulator of the environment to plan possible future scenarios but which scenarios are explored still depends on the neural network's heuristics.
In contrast, MuZero does not have access to an environment simulator during planning and explores futures scenarios using a learned state-transition model.
