### ISSUE TITLE
Using continuous rewards (i.e., non ternary games)

### ISSUE THREAD

**Issue by MonliH** [jonathan-laurent/AlphaZero.jl#77]
Is there a way to use continuous rewards with this awesome library? I'm trying to write an agent for a game without strict ternary outcomes (i.e., not 0, -1, or 1), as player needs to maximize a score. It doesn't really feel right to make the player with a greater score win, as the agent is trying to maximize a chess evaluation (in which case an evaluation of ~0.1 isn't too significant, but an eval of 1 is).

Is there any way to do this? When trying to return numbers from `GI.white_reward` that aren't 1 0 or -1, I get an assertion error triggered in [benchmark.jl](https://github.com/jonathan-laurent/AlphaZero.jl/blob/master/src/benchmark.jl#L115). This makes sense as the code just above the line liked only counts those exact values.

**Comment by jonathan-laurent** [comment]
You can have continuous rewards but then you must set the [`ternary_rewards`](https://github.com/jonathan-laurent/AlphaZero.jl/blob/615548f0abb12e31c7df6a40a38c9ab3b3411cd1/src/params.jl#L327) hyperparameter to `false`. The assertion you pointed to should never execute in this case (if it does, this is a bug).

**Comment by MonliH** [comment]
Oh wow, I completely missed that parameter. Thanks, it worked!
