### ISSUE TITLE
Iterative vs continuous learning

### ISSUE THREAD

**Issue by casper2002casper** [jonathan-laurent/AlphaZero.jl#81]
While AlphaGo Zero uses iterative learning, where first self-play is performed and afterwards the network is trained and pitted against the old network, the original AlphaZero implementation from Deepmind uses continuous learning. Relevant part of the [paper](https://arxiv.org/pdf/1712.01815.pdf):

> In AlphaGo Zero, self-play games were generated by the best player from all previous iterations. After each iteration of training, the performance of the new player was measured against the best player; if it won by a margin of 55% then it replaced the best player and self-play games were subsequently generated by this new player. In contrast, AlphaZero simply maintains a single neural network that is updated continually, rather than waiting for an iteration to complete. Self-play games are generated by using the latest parameters for this neural network, omitting the evaluation step and the selection of best player.

I'm not familiar with the bottlenecks of the current implementation, but implementing continuous learning might improve performance in CPU limited setups, as the GPU can both evaluate position while self playing and optimize the network simultaneously.

**Comment by jonathan-laurent** [comment]
AlphaZero.jl uses iterative training indeed, although you can disable the network pitting stage.
On a small number of machines/GPUs, this is a good tradeoff between efficiency and simplicity because self-play takes about 10x more time than network updates. I am thinking of implementing continuous distributed learning as you suggest, which would indeed enable the system to scale more easily to a large number of machines.

**Comment by idevcde** [comment]
>I'm not familiar with the bottlenecks of the current implementation, but implementing continuous learning might improve performance in CPU limited setups, as the GPU can both evaluate position while self playing and optimize the network simultaneously.

Based on my current knowledge about the topic, the first part of the iteration is performing pretty well on CPUs. The bottlenect is the second to fourth part of the iteration as it seems to be running only on one core.
