### ISSUE TITLE
Debugging in VS Code

### ISSUE THREAD

**Issue by casper2002casper** [jonathan-laurent/AlphaZero.jl#84]
I can't get debugging working in VS Code for this package. I followed [this guide](https://www.julia-vscode.org/docs/stable/userguide/debugging/) but using both methods described in the guide it says it is debugging, but breakpoints aren't triggered. I've adjusted the number of workers to 1 to simplify debugging but to no avail.

**Comment by casper2002casper** [comment]
Seems to be caused by VS Code not being able to handle parallel processes (or I'm doing something wrong), is there a better alternative method for debugging?

**Comment by jonathan-laurent** [comment]
Unfortunately, I am not familiar with the Julia debugger. I've heard it is not very mature yet though and I would not be surprised if spawning several processes is not currently supported.

Have you tried using the debugger on a single function that does not spawn threads or distributed processes?

**Comment by casper2002casper** [comment]
On single processes it works correctly, however at the mapreduce function it loses connection. I guess I'll use prints for now.

**Comment by jonathan-laurent** [comment]
Thanks for the update.
Also, don't hesitate to raise the issue with the debugger devs!
